BUILD=build
BUILD_DEBUGGER=$(BUILD)/Debugger
LOCKER_PROGRAM_DEBUG=$(BUILD_DEBUGGER)/src/locker

BUILD_DEVELOPMENT=$(BUILD)/Development
LOCKER_PROGRAM_DEV=$(BUILD_DEVELOPMENT)/src/locker

BUILD_RELEASE=$(BUILD)/Release
LOCKER_PROGRAM_RELEASE=$(BUILD_RELEASE)/src/locker

SRC=src

PROJECT_CMAKE=CMakeLists.txt
LOCKER_CMAKE=$(SRC)/CMakeLists.txt

MAKE=cmake --build

$(BUILD_DEVELOPMENT): $(PROJECT_CMAKE) $(LOCKER_CMAKE)
	cmake -S . -B $(BUILD_DEVELOPMENT) -DCMAKE_BUILD_TYPE=Development

$(BUILD_DEBUGGER): $(PROJECT_CMAKE) $(LOCKER_CMAKE)
	cmake -S . -B $(BUILD_DEBUGGER) -DCMAKE_BUILD_TYPE=Debugger

$(BUILD_RELEASE): $(PROJECT_CMAKE) $(LOCKER_CMAKE)
	cmake -S . -B $(BUILD_RELEASE) -DCMAKE_BUILD_TYPE=Release

$(LOCKER_PROGRAM_DEV): $(BUILD_DEVELOPMENT) $(SRC)
	$(MAKE) $(BUILD_DEVELOPMENT)

$(LOCKER_PROGRAM_RELEASE): $(BUILD_RELEASE) $(SRC)
	$(MAKE) $(BUILD_RELEASE)

$(LOCKER_PROGRAM_DEBUG): $(BUILD_DEBUGGER) $(SRC)
	$(MAKE) $(BUILD_DEBUGGER)

.PHONY: run
run: $(LOCKER_PROGRAM_DEV)
	LOCKER_PATH=development $(BUILD_DEVELOPMENT)/src/locker

.PHONY: install
install: $(LOCKER_PROGRAM_RELEASE)
	mkdir -p $(INSTALL_DIR)/locker
	mkdir -p $(INSTALL_DIR)/locker/bin
	mkdir -p $(INSTALL_DIR)/locker/lockers
	cp $(LOCKER_PROGRAM_RELEASE) $(INSTALL_DIR)/locker/bin

.PHONY: clean
clean:
	@rm -rf $(BUILD)/*
